spring:
  kafka:
    properties:
      basic:
        auth:
          credentials:
            source: "USER_INFO"
          user:
            info: "5AYWZLLUJQMJ2M2S:mrdJSj65oD/S33IntyAV0j7Khj59ZAiZRABEZTCsxwdagvZ3UzBnd5doBEKvByrA"
      schema:
        registry:
          url: "https://psrc-95km5.eu-central-1.aws.confluent.cloud"
      bootstrap:
        servers: "pkc-xmzwx.europe-central2.gcp.confluent.cloud:9092"
      security:
        protocol: "SASL_SSL"
      sasl:
        mechanism: "PLAIN"
        jaas:
          config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='ILWH6WLEBGT3X3VW' password='nbVLvD8kev9d0OZQUsrw4k36W7zimib6HmcN8NMCIG/KHSN27pED3duXIx3vYhgi';"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.IntegerSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.IntegerDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
    streams:
      application-id: "word-count-app"